### ISSUE TITLE
A critical, issue (because of me...)

### ISSUE THREAD

**Issue by ammardevz** [hyultis/rust_Hconfig#1]
Hi,

I’m AmmarDev, the owner of the rusty_json crate. I wanted to inform you about a critical issue that was present in previous versions of rusty_json. The parser had a problem handling escape characters, which could lead to incorrect parsing.

To ensure better stability and fix this issue, please update to rusty_json version 2.0.5 or later. The problem has been resolved in this version.

Thank you for your attention to this matter.

Best regards,
AmmarDev

**Comment by hyultis** [comment]
Sorry, a bit late, but this is fixed, thanks for the information
